steps:
- id: 'compile'
  name: maven:3.8.3-jdk-11-slim
  entrypoint: mvn
  args: ['compile']


- id: 'test'
  name: maven:3.8.3-jdk-11-slim
  entrypoint: mvn
  args: ['test']  

- id: 'branch-build'
  name: 'gcr.io/cloud-builders/docker'
  waitFor: 'test'
  entrypoint: 'bash'
  args:  
  - '-c'
  - |
    [["$BRANCH_NAME" == "master" ]] && docker build -t gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA .

- id: 'master-docker-build'
  name: 'gcr.io/cloud-builders/docker'
  waitFor: 'test'
  entrypoint: 'bash'  
  args:
  - '-c'
  - |
    [["$BRANCH_NAME" == "master" ]] && docker build -t gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA -t gcr.io/$PROJECT_ID/$REPO_NAME:latest .

- id: 'branch-docker-build'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:  
  - '-c'
  - |
    [["$BRANCH_NAME" == "master" ]] && docker push -t gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA .

- id: 'docker-tag-push'
  name: 'gcr.io/cloud-builders/docker'
  waitFor: ['master-docker-build', 'branch-docker-build']
  args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/$REPO_NAME']

