steps:
- id: 'compile'
  name: maven:3.8.3-jdk-11-slim
  entrypoint: mvn
  args: ['compile']


- id: 'test'
  name: maven:3.8.3-jdk-11-slim
  entrypoint: mvn
  args: ['test']  

- id: 'master-docker-build'
  name: 'gcr.io/cloud-builders/docker'
  waitFor: ['test']
  entrypoint: 'bash'  
  args: ['-c', '[["$BRANCH_NAME" == "master" ]] && docker build -t gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA -t gcr.io/$PROJECT_ID/$REPO_NAME:latest . || exit 0']

- id: 'branch-docker-build'
  name: 'gcr.io/cloud-builders/docker'
  waitFor: ['test']
  entrypoint: 'bash'
  args: ['-c', '[["$BRANCH_NAME" != "master" ]] && docker build -t gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA . || exit 0']

- id: 'docker-tag-push'
  name: 'gcr.io/cloud-builders/docker'
  waitFor: ['master-docker-build', 'branch-docker-build']
  args: ['image', 'push', '--all-tags', 'gcr.io/$PROJECT_ID/$REPO_NAME']

