version: '3'
services:
  partydj-server:
    image: gsugambit/partydj-server:latest
    restart: always
    ports:
      - 19191:8080
    environment:
      SPRING_PROFILES_ACTIVE: "production"
      JAVA_OPTS: "-Xms512m -Xmx1024m -XX:PermSize=512m -XX:MaxPermSize=1024m -XX:+UseG1GC"

networks:
  default:
    external:
      name: partydj_network
## docker network create partydj_network